[build]
builder = "NIXPACKS"

[[cron]]
schedule = "0 20 * * 2"
command  = "python tools/settle_report.py --send"

[[cron]]
schedule = "0 21 * * 2"
command  = "python tools/settle_report.py --send"

[[cron]]
schedule = "0 22 * * 2"
command  = "python tools/make_report.py --send"

[[cron]]
schedule = "0 23 * * 2"
command  = "python tools/make_report.py --send"
